### ISSUE TITLE
SUB_SESSION_FOLDER vs SESSION_SUB_FOLDER

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/IBL_root#29]
After successfully installing Bonsai and pyBpod, running test_basicChoiceWorld gives the following error

```
Traceback (most recent call last):
  File "C:\IBL_root\pybpod_projects\IBL\tasks\basicChoiceWorld\basicChoiceWorld.py", line 63, in <module>
    dst = os.path.join(sph.SUB_SESSION_FOLDER, 'Gabor2D/')
AttributeError: 'session_param_handler' object has no attribute 'SUB_SESSION_FOLDER'
```

in session_param_handler, only `SESSION_SUB_FOLDER` is defined. Changing this on line  64 and 67 of basicChoiceWorld.py solves the problem.

**Comment by nbonacchi** [comment]
That should be changed already...
maybe forgot to merge it

**Comment by anne-urai** [comment]
Hm weird, it seems correct on the master branch https://github.com/int-brain-lab/pybpod_projects/blob/master/IBL/tasks/basicChoiceWorld/basicChoiceWorld.py but for some reason my git pull didn't grab that version...
