### ISSUE TITLE
Bonsai installation location

### ISSUE THREAD

**Issue by anne-urai** [int-brain-lab/IBL_root#30]
BasicChoiceWorld.py assumes the path to Bonsai is
`bns = 'C:/Users/User/AppData/Local/Bonsai/Bonsai64.exe'`
but this is not specified in the installation instructions. 
In my case, changing line 68 to ` bns = 'C:\Bonsai-2.3\Bonsai64.exe'` correctly starts Bonsai.

When Bonsai first launches, the user is prompted by Windows Firewall. It may be good to include this in the instructions so as to specify to accept those permission requests

**Comment by nbonacchi** [comment]
Yes, it assumes the Bonsai default installation folder...
